const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const defaultClient={businessName:'Your Demo Client',businessType:'Local business',businessLocation:'Northampton',idealCustomer:'Local customers',primaryGoal:'More customers',marketingBudget:500,usp:'Great service, strong local reputation and a distinctive customer experience.',problems:'Inconsistent content, weak repeat-customer system and no structured monthly offer strategy.'};
const demoClient={businessName:'Nourish Northampton',businessType:'Independent café & lifestyle venue',businessLocation:'Northampton',idealCustomer:'Students, young professionals, remote workers and health-conscious locals',primaryGoal:'More repeat visits',marketingBudget:750,usp:'A modern café experience with strong visual identity, community potential and room to expand beyond coffee.',problems:'Social content can be more conversion-focused, offers are not systemised, and there is an opportunity to increase repeat visits and average spend.'};
let client=JSON.parse(localStorage.getItem('growlocal-client'))||defaultClient;
let clientWorkspaces=JSON.parse(localStorage.getItem('growlocal-clients')||'null')||[{id:'client-'+Date.now(),...client}];
let activeClientId=localStorage.getItem('growlocal-active-client')||clientWorkspaces[0].id;
client=clientWorkspaces.find(c=>c.id===activeClientId)||clientWorkspaces[0];
let activity=JSON.parse(localStorage.getItem('growlocal-activity')||'[]');
let completedDays=new Set(JSON.parse(localStorage.getItem('growlocal-plan-done-'+activeClientId)||localStorage.getItem('growlocal-plan-done')||'[]'));
const pageTitles={dashboard:'Good morning',plan:'Growth plan',content:'Content studio',offers:'Campaign lab',reviews:'Reputation',insights:'Insights',leads:'Lead pipeline',reports:'Client reports',agency:'Agency HQ',clients:'Client profile',sales:'GrowLocal offer',account:'Account & billing'};
const breadcrumbTitles={dashboard:'Overview',plan:'Growth plan',content:'Content studio',offers:'Campaigns',reviews:'Reputation',insights:'Insights',leads:'Lead pipeline',reports:'Client reports',agency:'Agency HQ',clients:'Client profile',sales:'GrowLocal offer',account:'Account & billing'};
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;$('toastRoot').appendChild(t);setTimeout(()=>t.remove(),1900)}
function navTo(page){$$('.page').forEach(p=>p.classList.remove('active'));$$('.nav-item').forEach(n=>n.classList.remove('active'));$(page).classList.add('active');const nav=document.querySelector(`[data-page="${page}"]`);if(nav)nav.classList.add('active');$('breadcrumb').textContent=breadcrumbTitles[page];$('pageTitle').innerHTML=page==='dashboard'?`Good morning <span class="title-muted">— here’s what can grow.</span>`:pageTitles[page];$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>navTo(btn.dataset.page)));$$('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>navTo(btn.dataset.jump)));
function syncForm(){Object.entries(client).forEach(([k,v])=>{if($(k))$(k).value=v});$('sidebarBusiness').textContent=client.businessName||'Unnamed client';$('heroBusiness').textContent=client.businessName||'your client'}
function readForm(){client={businessName:$('businessName').value||'Unnamed client',businessType:$('businessType').value||'Local business',businessLocation:$('businessLocation').value||'',idealCustomer:$('idealCustomer').value||'Local customers',primaryGoal:$('primaryGoal').value,marketingBudget:Number($('marketingBudget').value||0),usp:$('usp').value||'',problems:$('problems').value||''};return client}
function saveClient(){if($('clients').classList.contains('active'))readForm();persistActiveClient();syncForm();renderDashboard();renderReport();renderClientWorkspaces();logActivity('Client updated',client.businessName);toast('Client saved locally')}
$('saveBtn').addEventListener('click',saveClient);$('demoBtn').addEventListener('click',()=>{client={...demoClient,id:activeClientId};persistActiveClient();syncForm();renderDashboard();generatePlan();renderReport();renderClientWorkspaces();logActivity('Demo loaded',client.businessName);toast('Nourish demo loaded')});$('workspaceBtn').addEventListener('click',openWorkspaceModal);$('analyseBtn').addEventListener('click',()=>{readForm();saveClient();generatePlan();navTo('dashboard');toast('Growth analysis refreshed')});
function renderDashboard(){const score=Math.min(94,60+(client.usp?6:0)+(client.problems?5:0)+(client.marketingBudget>=500?5:0)+(client.idealCustomer?4:0));$('growthScore').textContent=score;const circumference=314.16;$('scoreRing').style.strokeDashoffset=(circumference*(1-score/100)).toFixed(1);const budget=Number(client.marketingBudget)||500;const opportunity=Math.round((budget*4.56)/10)*10;$('revenueOpportunity').textContent=`£${opportunity.toLocaleString('en-GB')}`;$('impactValue').textContent=`£${(opportunity/1000).toFixed(1)}k`;$('campaignValue').textContent=`£${Math.round(opportunity*.23/10)*10}`;const priorities=[['Build a 14-day return loop',`Give existing ${client.idealCustomer||'customers'} a reason to return quickly.`,'Retention'],['Create one measurable hero offer',`Tie the campaign directly to ${client.primaryGoal.toLowerCase()} — one promise, one CTA.`,'Conversion'],['Turn proof into weekly content',`Use customer outcomes and local relevance instead of generic posting.`,'Visibility']];$('priorityList').innerHTML=priorities.map((p,i)=>`<div class="priority-item"><div class="priority-num">0${i+1}</div><div class="priority-text"><strong>${p[0]}</strong><span>${p[1]}</span></div><div class="impact">${p[2]}</div></div>`).join('')}
const themes=[['Proof that converts','Share a customer result, reaction or reason people choose the business.','Social'],['Hero offer','Promote one simple, trackable campaign with a clear reason to act now.','Campaign'],['Behind the scenes','Show what creates the quality customers experience.','Content'],['Local relevance',`Connect the business to ${client.businessLocation||'the local area'} and its community.`,'Community'],['Education','Teach one useful thing the ideal customer should know before buying.','Value'],['Founder / team','Make the people behind the business visible and memorable.','Trust'],['Return visit','Give current customers a specific reason to come back within 14 days.','Retention'],['Objection remover','Answer a common question or doubt before it blocks a purchase.','Conversion']];
function generatePlan(){const actions=['Publish','Story sequence','Direct outreach','Campaign','Review push','Partnership'];$('planGrid').innerHTML=Array.from({length:30},(_,i)=>{const t=themes[i%themes.length],day=i+1,done=completedDays.has(day)?' done':'';return `<article class="day-card${done}" data-day="${day}"><div class="day">DAY ${String(day).padStart(2,'0')} · ${actions[i%actions.length].toUpperCase()}</div><h4>${t[0]}</h4><p>${t[1]} Keep it specific to ${client.businessName}.</p><span class="day-type">${t[2]}</span></article>`}).join('');$$('.day-card').forEach(card=>card.addEventListener('click',()=>{const day=Number(card.dataset.day);completedDays.has(day)?completedDays.delete(day):completedDays.add(day);localStorage.setItem('growlocal-plan-done',JSON.stringify([...completedDays]));card.classList.toggle('done');updatePlanProgress()}));updatePlanProgress()}
function updatePlanProgress(){const pct=Math.round(completedDays.size/30*100);$('planProgress').style.width=`${pct}%`;$('planPercent').textContent=`${pct}%`}
$('generatePlanBtn').addEventListener('click',()=>{completedDays.clear();localStorage.setItem('growlocal-plan-done','[]');generatePlan();toast('Fresh 30-day plan created')});$('resetPlanBtn').addEventListener('click',()=>{completedDays.clear();localStorage.setItem('growlocal-plan-done','[]');generatePlan();toast('Plan progress reset')});
$$('#platformChoices .choice').forEach(btn=>btn.addEventListener('click',()=>{$$('#platformChoices .choice').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('platform').value=btn.dataset.value}));
function generateContent(){const platform=$('platform').value,goal=$('contentGoal').value,topic=$('contentTopic').value.trim()||'what makes the business worth choosing',name=client.businessName||'the business',place=client.businessLocation||'your area';const posts=[{type:'CONVERSION',h:`The “why now” post`,p:`If ${place} has been meaning to try ${name}, this is the reason to make the visit this week. Lead with ${topic.toLowerCase()}, show the outcome in the first line or first 2 seconds, then make the next step obvious. CTA: visit, book or message today.`,score:'High intent'},{type:'TRUST',h:'Proof before promotion',p:`Open with a real customer moment: what they noticed, loved or came back for. Then connect it to ${client.usp||'the quality of the experience'}. Close softly: “If that sounds like your kind of place, you know where to find us.”`,score:'Trust builder'},{type:'SHORT FORM',h:`${platform} hook + sequence`,p:`Hook: “One thing people don’t realise about ${client.businessType||'this local business'}…” Show 3 fast proof points around ${topic.toLowerCase()}. End on the customer outcome, not the product. Goal: ${goal.toLowerCase()}.`,score:'Fast reach'}];$('contentOutput').classList.remove('empty-state');$('contentOutput').innerHTML=posts.map((x,i)=>`<article class="content-card"><div class="content-meta"><span>${x.type}</span><span>Concept 0${i+1}</span></div><h4>${x.h}</h4><p>${x.p}</p><footer><span>✦ ${x.score}</span><button class="copy-content">Copy concept</button></footer></article>`).join('');$$('.copy-content').forEach((b,i)=>b.addEventListener('click',()=>copyText(posts[i].p,'Concept copied')))}
$('generateContentBtn').addEventListener('click',()=>{generateContent();logActivity('Content generated',client.businessName)});$('clearContent').addEventListener('click',()=>{$('contentOutput').className='stack empty-state';$('contentOutput').innerHTML='<div class="empty-orb">✦</div><h4>Your content will appear here</h4><p>Give GrowLocal a brief and it will turn it into commercially useful content concepts.</p>'});
function generateOffer(){const goal=$('offerGoal').value,spend=Number($('avgSpend').value||18),day=$('quietDay').value,intensity=Number($('intensity').value||2);let title=`${day} Return Loop`,mechanic=`Spend £${Math.round(spend*1.25)}+ on ${day} and unlock a targeted return-visit bonus valid for 14 days.`,uplift=Math.round(spend*(intensity*.35)*40);if(goal.includes('new customers')){title='Local First-Visit Trigger';mechanic='Create a first-visit value add that requires a clear campaign code, then capture permission for a follow-up that drives visit two.'}if(goal.includes('average spend')){title='Smart Bundle Upgrade';mechanic=`Pair the core purchase with a high-margin add-on and price the bundle around £${Math.round(spend*(1.15+intensity*.06))}. Avoid discounting the whole basket.`}if(goal.includes('quiet-day')){title=`Own ${day}`;mechanic=`Give ${day} a named reason to exist: a time-limited bundle or experience that only runs that day, designed around current average spend of £${spend}.`}const redemption=intensity===1?'8–12%':intensity===2?'12–18%':'18–25%';$('offerOutput').className='';$('offerOutput').innerHTML=`<div class="offer-card"><span class="overline">${goal.toUpperCase()}</span><h4>${title}</h4><div class="offer-value">+£${uplift.toLocaleString('en-GB')}</div><p>Estimated campaign upside if executed consistently. ${mechanic}</p><div class="offer-metrics"><div><span>Target redemption</span><b>${redemption}</b></div><div><span>Run length</span><b>14 days</b></div><div><span>Primary KPI</span><b>${goal.includes('average')?'AOV':'Repeat visits'}</b></div></div><p><strong style="color:#dce8e2">Activation:</strong> 3 social posts, one in-store prompt and one direct outreach message. Track redemptions separately so the owner can see whether the campaign paid for itself.</p></div>`}
$('generateOfferBtn').addEventListener('click',()=>{generateOffer();logActivity('Campaign built',client.businessName)});
function generateReply(){const review=$('reviewText').value.trim(),tone=$('reviewTone').value,name=client.businessName||'our team';if(!review){toast('Paste a review first');return}const positive=/great|amazing|love|excellent|friendly|perfect|best|delicious|fantastic|recommend|lovely/i.test(review),negative=/bad|poor|slow|rude|awful|disappointed|cold|wrong|wait|terrible|avoid/i.test(review);let out;if(negative&&!positive){$('sentimentPill').textContent='Needs attention';out=`Thank you for sharing this with us. We’re sorry your experience at ${name} didn’t meet the standard we aim for. We’d like to understand what happened and put it right, so please contact us directly with the details of your visit and a member of the team will follow this up properly.`}else if(positive){$('sentimentPill').textContent='Positive';out=`Thank you for such a lovely review. We’re really pleased you enjoyed your experience with ${name}, and we appreciate you taking the time to share it. Feedback like this means a lot to the team and we hope to welcome you back again soon.`}else{$('sentimentPill').textContent='Neutral';out=`Thank you for taking the time to leave feedback about your visit to ${name}. We really appreciate hearing from our customers and will share your comments with the team. We hope to see you again soon.`}if(tone==='Short and direct')out=out.split('. ').slice(0,2).join('. ')+'.';$('reviewOutput').textContent=out;$('reviewOutput').classList.remove('muted')}
$('generateReplyBtn').addEventListener('click',()=>{generateReply();if($('reviewText').value.trim())logActivity('Review response created',client.businessName)});$('copyReview').addEventListener('click',()=>copyText($('reviewOutput').textContent,'Review response copied'));
function copyText(text,msg='Copied'){navigator.clipboard?.writeText(text).then(()=>toast(msg)).catch(()=>toast('Copy unavailable in this browser'))}
const pitch=`I help local businesses turn the marketing they already do into a simple monthly growth system. Instead of random posts and discounts, we focus on the few actions most likely to increase customers, repeat visits and average spend — then track whether they actually work. I set the system up for £199, then run the monthly growth plan from £149.`;$('copyPitchBtn').addEventListener('click',()=>copyText(pitch,'Sales pitch copied'));$('copyPitchInline').addEventListener('click',()=>copyText(pitch,'Sales pitch copied'));
$('simulateBtn').addEventListener('click',()=>{const vals={customers:Math.round(Number($('customersMetric').textContent)*1.084),aov:(parseFloat($('aovMetric').textContent.replace('£',''))+1.2).toFixed(2),repeat:Math.round(parseFloat($('repeatMetric').textContent)+4),reviews:Number($('reviewsMetric').textContent)+6};$('customersMetric').textContent=vals.customers;$('aovMetric').textContent=`£${vals.aov}`;$('repeatMetric').textContent=`${vals.repeat}%`;$('reviewsMetric').textContent=vals.reviews;toast('Next-month scenario simulated')});
function renderReport(){if(!$('clientReport'))return;const budget=Number(client.marketingBudget)||500;const opportunity=Math.round((budget*4.56)/10)*10;const score=Math.min(94,60+(client.usp?6:0)+(client.problems?5:0)+(client.marketingBudget>=500?5:0)+(client.idealCustomer?4:0));$('reportBusiness').textContent=client.businessName||'Client';$('reportLocation').textContent=`${client.businessLocation||'Local'} · ${client.businessType||'Business'}`;$('reportScore').textContent=score;$('reportUplift').textContent=`£${opportunity.toLocaleString('en-GB')}`;$('reportCompletion').textContent=`${Math.round(completedDays.size/30*100)}%`;$('reportFocus').textContent=client.primaryGoal.includes('repeat')?'Retention':client.primaryGoal.includes('spend')?'Average spend':client.primaryGoal.includes('lead')?'Lead generation':'Acquisition';$('reportMonth').textContent=new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(new Date());}
$('printReportBtn')?.addEventListener('click',()=>{renderReport();logActivity('Report exported',client.businessName);window.print()});
function openCommand(){ $('commandBackdrop').classList.add('open');setTimeout(()=>$('commandInput').focus(),50)}function closeCommand(){$('commandBackdrop').classList.remove('open');$('commandInput').value='';filterCommands('')};function filterCommands(q){$$('.command-palette>button').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q.toLowerCase())?'grid':'none')}$('searchBtn').addEventListener('click',openCommand);$('commandBackdrop').addEventListener('click',e=>{if(e.target===$('commandBackdrop'))closeCommand()});$('commandInput').addEventListener('input',e=>filterCommands(e.target.value));$$('[data-command-page]').forEach(b=>b.addEventListener('click',()=>{navTo(b.dataset.commandPage);closeCommand()}));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape')closeCommand()});$('mobileMenu').addEventListener('click',()=>$('sidebar').classList.toggle('open'));

let leads=JSON.parse(localStorage.getItem('growlocal-leads')||'[]');
function renderLeads(){
  const list=$('leadList'); if(!list)return;
  $('leadCountBadge').textContent=leads.length;
  const active=leads.filter(l=>l.stage!=='Won');
  $('openLeadsMetric').textContent=active.length;
  $('pipelineValueMetric').textContent='£'+active.reduce((s,l)=>s+Number(l.value||0),0).toLocaleString('en-GB');
  $('proposalMetric').textContent=leads.filter(l=>l.stage==='Proposal').length;
  $('wonMetric').textContent=leads.filter(l=>l.stage==='Won').length;
  if(!leads.length){list.innerHTML='<div class="empty-state compact-empty"><div class="empty-orb">◉</div><h4>No leads yet</h4><p>Add local businesses you want to approach and GrowLocal will keep the pipeline organised.</p></div>';return}
  list.innerHTML=leads.map((l,i)=>`<article class="lead-row"><div class="lead-main"><div class="lead-avatar">${(l.name||'?').slice(0,2).toUpperCase()}</div><div><strong>${l.name}</strong><span>${l.contact||'Owner / manager'} · ${l.next||'No next action set'}</span></div></div><div class="lead-stage stage-${l.stage.toLowerCase()}">${l.stage}</div><div class="lead-value">£${Number(l.value||0).toLocaleString('en-GB')}<span>/mo</span></div><button class="btn btn-mini advance-lead" data-i="${i}">${l.stage==='Won'?'Won ✓':'Advance →'}</button><button class="icon-btn delete-lead" data-i="${i}">×</button></article>`).join('');
  $$('.advance-lead').forEach(b=>b.addEventListener('click',()=>{const stages=['Prospect','Contacted','Meeting','Proposal','Won'];let l=leads[Number(b.dataset.i)];if(l.stage!=='Won')l.stage=stages[Math.min(stages.indexOf(l.stage)+1,stages.length-1)];persistLeads()}));
  $$('.delete-lead').forEach(b=>b.addEventListener('click',()=>{leads.splice(Number(b.dataset.i),1);persistLeads()}));
}
function persistLeads(){localStorage.setItem('growlocal-leads',JSON.stringify(leads));renderLeads();renderAgency()}
function openLeadModal(){$('leadModal').classList.add('open');$('leadName').focus()}
function closeLeadModal(){$('leadModal').classList.remove('open')}
$('addLeadBtn')?.addEventListener('click',openLeadModal);$('closeLeadModal')?.addEventListener('click',closeLeadModal);$('leadModal')?.addEventListener('click',e=>{if(e.target===$('leadModal'))closeLeadModal()});
$('saveLeadBtn')?.addEventListener('click',()=>{const name=$('leadName').value.trim();if(!name){toast('Add a business name first');return}leads.unshift({name,contact:$('leadContact').value.trim(),stage:$('leadStage').value,value:Number($('leadValue').value||0),next:$('leadNext').value.trim()});persistLeads();['leadName','leadContact','leadNext'].forEach(id=>$(id).value='');closeLeadModal();toast('Opportunity added')});


function persistActiveClient(){
  if(!client.id) client.id=activeClientId||('client-'+Date.now());
  activeClientId=client.id;
  const i=clientWorkspaces.findIndex(c=>c.id===client.id);
  if(i>=0) clientWorkspaces[i]={...client}; else clientWorkspaces.push({...client});
  localStorage.setItem('growlocal-client',JSON.stringify(client));
  localStorage.setItem('growlocal-clients',JSON.stringify(clientWorkspaces));
  localStorage.setItem('growlocal-active-client',activeClientId);
}
function initials(name='Client'){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'CL'}
function renderClientWorkspaces(){
  const render=(target,modal=false)=>{if(!target)return;target.innerHTML=clientWorkspaces.map(c=>`<button class="workspace-client ${c.id===activeClientId?'active':''}" data-client-id="${c.id}"><span class="workspace-client-avatar">${initials(c.businessName)}</span><div><strong>${c.businessName||'Unnamed client'}</strong><small>${c.businessType||'Local business'} · ${c.businessLocation||'Location not set'}</small></div>${c.id===activeClientId?'<span class="active-dot"></span>':''}</button>`).join('');target.querySelectorAll('[data-client-id]').forEach(b=>b.addEventListener('click',()=>switchClient(b.dataset.clientId,modal)))};
  render($('clientWorkspaceList')); render($('workspaceModalList'),true);
  if($('clientCountBadge'))$('clientCountBadge').textContent=clientWorkspaces.length;
}
function switchClient(id,close=false){
  if($('clients')?.classList.contains('active')){readForm();persistActiveClient()}
  const next=clientWorkspaces.find(c=>c.id===id); if(!next)return;
  activeClientId=id; client={...next}; completedDays=new Set(JSON.parse(localStorage.getItem('growlocal-plan-done-'+id)||'[]'));
  localStorage.setItem('growlocal-active-client',id);localStorage.setItem('growlocal-client',JSON.stringify(client));
  syncForm();renderDashboard();generatePlan();renderReport();renderClientWorkspaces();logActivity('Workspace opened',client.businessName);if(close)closeWorkspaceModal();toast(`Switched to ${client.businessName}`)
}
function createNewClient(){
  const id='client-'+Date.now();
  client={...defaultClient,id,businessName:'New client',businessType:'Local business',businessLocation:'',idealCustomer:'Local customers',usp:'',problems:''};
  activeClientId=id;clientWorkspaces.push({...client});completedDays=new Set();persistActiveClient();syncForm();renderDashboard();generatePlan();renderReport();renderClientWorkspaces();closeWorkspaceModal();navTo('clients');$('businessName')?.focus();logActivity('Client created','New client');toast('New client workspace created')
}
function openWorkspaceModal(){renderClientWorkspaces();$('workspaceModal').classList.add('open')}
function closeWorkspaceModal(){$('workspaceModal').classList.remove('open')}
function logActivity(action,subject){
  activity.unshift({action,subject:subject||client.businessName||'Workspace',at:new Date().toISOString()});activity=activity.slice(0,12);localStorage.setItem('growlocal-activity',JSON.stringify(activity));renderActivity()
}
function renderActivity(){const root=$('activityFeed');if(!root)return;if(!activity.length){root.innerHTML='<div class="activity-item"><span>Ready</span><strong>No activity yet</strong><small>Your recent work will appear here.</small></div>';return}root.innerHTML=activity.slice(0,9).map(a=>`<div class="activity-item"><span>${a.action}</span><strong>${a.subject}</strong><small>${new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(a.at))}</small></div>`).join('')}
$('newClientBtn')?.addEventListener('click',createNewClient);$('modalNewClientBtn')?.addEventListener('click',createNewClient);$('closeWorkspaceModal')?.addEventListener('click',closeWorkspaceModal);$('workspaceModal')?.addEventListener('click',e=>{if(e.target===$('workspaceModal'))closeWorkspaceModal()});$('clearActivityBtn')?.addEventListener('click',()=>{activity=[];localStorage.setItem('growlocal-activity','[]');renderActivity();toast('Activity cleared')});$('billingDemoBtn')?.addEventListener('click',()=>toast('Billing UI is ready — live Stripe credentials are the remaining connection step'));
// Keep each client's plan completion separate from V5 onward.
const originalUpdatePlanProgress=updatePlanProgress;updatePlanProgress=function(){localStorage.setItem('growlocal-plan-done-'+activeClientId,JSON.stringify([...completedDays]));originalUpdatePlanProgress()};
renderClientWorkspaces();renderActivity();



function clientScore(c){return Math.min(94,60+(c.usp?6:0)+(c.problems?5:0)+(Number(c.marketingBudget)>=500?5:0)+(c.idealCustomer?4:0))}
function renderAgency(){
  if(!$('agencyPortfolio'))return;
  const won=leads.filter(l=>l.stage==='Won');
  const open=leads.filter(l=>l.stage!=='Won');
  const mrr=won.reduce((sum,l)=>sum+Number(l.value||0),0);
  const pipeline=open.reduce((sum,l)=>sum+Number(l.value||0),0);
  const progressed=leads.filter(l=>l.stage!=='Prospect').length;
  const closeRate=progressed?Math.round(won.length/progressed*100):0;
  $('agencyMrr').textContent=`£${mrr.toLocaleString('en-GB')}`;
  $('agencyClients').textContent=clientWorkspaces.length;
  $('agencyPipeline').textContent=`£${pipeline.toLocaleString('en-GB')}`;
  $('agencyCloseRate').textContent=`${closeRate}%`;
  $('agencyPortfolio').innerHTML=clientWorkspaces.map(c=>{const score=clientScore(c),done=JSON.parse(localStorage.getItem('growlocal-plan-done-'+c.id)||'[]').length;return `<button class="portfolio-row" data-agency-client="${c.id}"><span class="workspace-client-avatar">${initials(c.businessName)}</span><div><strong>${c.businessName||'Unnamed client'}</strong><small>${c.businessType||'Local business'} · ${c.businessLocation||'Location not set'}</small></div><span class="portfolio-progress"><i style="width:${Math.round(done/30*100)}%"></i></span><b>${score}</b></button>`}).join('');
  $$('[data-agency-client]').forEach(b=>b.addEventListener('click',()=>{switchClient(b.dataset.agencyClient);navTo('dashboard')}));
  const focus=[];
  if(open.length)focus.push(['Move the pipeline',`${open.length} open opportunities worth £${pipeline.toLocaleString('en-GB')}/mo are waiting for a next action.`,'Open CRM','leads']);
  if(clientWorkspaces.length<5)focus.push(['Build proof fast','Aim for 3–5 clients before adding expensive infrastructure. Use reports to create case-study evidence.','Open reports','reports']);
  focus.push(['Protect retention',`Keep every client on one measurable campaign and one retention action each month.`,`Open growth plan`,'plan']);
  $('agencyFocus').innerHTML=focus.slice(0,3).map((f,i)=>`<div class="focus-row"><span>0${i+1}</span><div><strong>${f[0]}</strong><p>${f[1]}</p></div><button class="text-btn" data-focus-page="${f[3]}">${f[2]} →</button></div>`).join('');
  $$('[data-focus-page]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.focusPage)));
}
function duplicateActiveClient(){
  const id='client-'+Date.now();
  const copy={...client,id,businessName:`${client.businessName} Copy`};
  clientWorkspaces.push(copy);activeClientId=id;client=copy;completedDays=new Set();persistActiveClient();syncForm();renderClientWorkspaces();renderAgency();renderDashboard();generatePlan();renderReport();renderProposal();logActivity('Client duplicated',copy.businessName);toast('Client duplicated')
}
function deleteActiveClient(){
  if(clientWorkspaces.length<=1){toast('Keep at least one client workspace');return}
  const old=client.businessName;
  localStorage.removeItem('growlocal-plan-done-'+activeClientId);
  clientWorkspaces=clientWorkspaces.filter(c=>c.id!==activeClientId);
  client={...clientWorkspaces[0]};activeClientId=client.id;completedDays=new Set(JSON.parse(localStorage.getItem('growlocal-plan-done-'+activeClientId)||'[]'));persistActiveClient();syncForm();renderClientWorkspaces();renderAgency();renderDashboard();generatePlan();renderReport();renderProposal();logActivity('Client removed',old);toast('Client workspace deleted')
}
function exportBackup(){
  const planProgress={};clientWorkspaces.forEach(c=>planProgress[c.id]=JSON.parse(localStorage.getItem('growlocal-plan-done-'+c.id)||'[]'));
  const data={version:6,exportedAt:new Date().toISOString(),activeClientId,clients:clientWorkspaces,leads,activity,planProgress};
  const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`growlocal-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);logActivity('Workspace backup exported','GrowLocal OS');toast('Backup downloaded')
}
function importBackupFile(file){
  const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.clients)||!data.clients.length)throw new Error('Invalid backup');clientWorkspaces=data.clients;leads=Array.isArray(data.leads)?data.leads:[];activity=Array.isArray(data.activity)?data.activity:[];activeClientId=data.activeClientId&&clientWorkspaces.some(c=>c.id===data.activeClientId)?data.activeClientId:clientWorkspaces[0].id;client={...clientWorkspaces.find(c=>c.id===activeClientId)};Object.entries(data.planProgress||{}).forEach(([id,v])=>localStorage.setItem('growlocal-plan-done-'+id,JSON.stringify(v)));completedDays=new Set(JSON.parse(localStorage.getItem('growlocal-plan-done-'+activeClientId)||'[]'));persistActiveClient();localStorage.setItem('growlocal-leads',JSON.stringify(leads));localStorage.setItem('growlocal-activity',JSON.stringify(activity));syncForm();renderLeads();renderClientWorkspaces();renderAgency();renderActivity();renderDashboard();generatePlan();renderReport();renderProposal();toast('Backup restored successfully')}catch(e){toast('That backup file could not be restored')}};r.readAsText(file)
}
function proposalText(){
  const name=client.businessName||'your business',goal=(client.primaryGoal||'more customers').toLowerCase();
  return `GrowLocal growth proposal for ${name}\n\nThe opportunity\n${name} already has the foundations to grow. The next step is turning marketing activity into a repeatable system focused on ${goal}.\n\nWhat I would implement\n• A focused 30-day growth plan built around the highest-leverage actions.\n• One measurable monthly campaign designed to create customer action, not just engagement.\n• Conversion-led content and reputation support tied to the same commercial goal.\n• A monthly scorecard showing progress, opportunities and the next priorities.\n\nCommercial model\nSetup: £199 one-off\nGrowth Partner: £149/month\n\nThe aim is simple: make marketing easier to execute and easier to connect to revenue.`
}
function renderProposal(){if(!$('proposalPreview'))return;$('proposalPreview').innerHTML=proposalText().split('\n').map(x=>x?`<p>${x.replace(/^• /,'<span>•</span> ')}</p>`:'<div class="proposal-gap"></div>').join('')}
$('duplicateClientBtn')?.addEventListener('click',duplicateActiveClient);
$('deleteClientBtn')?.addEventListener('click',deleteActiveClient);
$('exportBackupBtn')?.addEventListener('click',exportBackup);
$('importBackupInput')?.addEventListener('change',e=>{if(e.target.files?.[0])importBackupFile(e.target.files[0]);e.target.value=''});
$('copyProposalBtn')?.addEventListener('click',()=>copyText(proposalText(),'Proposal copied'));
const basePersistActiveClient=persistActiveClient;persistActiveClient=function(){basePersistActiveClient();renderAgency();renderProposal()};
const baseRenderLeads=renderLeads;renderLeads=function(){baseRenderLeads();renderAgency()};
syncForm();renderDashboard();generatePlan();renderLeads();renderReport();renderClientWorkspaces();renderActivity();renderAgency();renderProposal();
